import { readFileSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { tokenize } from './lexer.js'
import { parse } from './parser.js'
import { compileToString } from './compiler.js'

export interface PrecompileResult {
  files: number
  output: string
}

function walkHtmlFiles(dir: string, baseDir: string): string[] {
  const result: string[] = []
  const entries = readdirSync(dir)
  for (const entry of entries) {
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      result.push(...walkHtmlFiles(fullPath, baseDir))
    } else if (entry.endsWith('.html')) {
      result.push(fullPath)
    }
  }
  return result
}

function compileFileToJs(sourcePath: string, outputPath: string): void {
  const content = readFileSync(sourcePath, 'utf-8')
  const ast = parse(tokenize(content))
  const code = compileToString(ast)
  const wrapped = `// Precompiled: ${relative(process.cwd(), sourcePath)}
export default function(data, helpers, escapeHTML) {
${code}
}
`
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, wrapped)
}

export function precompile(inputDir: string, outputDir: string): PrecompileResult {
  const files = walkHtmlFiles(inputDir, inputDir)

  let count = 0
  const barrel: string[] = []
  barrel.push('// Barrel generated by @nds-stack/bun-html precompile')
  barrel.push('')

  const exports: string[] = []

  for (const file of files) {
    const rel = relative(inputDir, file).replace(/\\/g, '/')
    const outPath = join(outputDir, rel + '.js')
    compileFileToJs(file, outPath)

    const importPath = './' + rel.replace(/\\/g, '/')
    const exportName = rel
      .replace(/[\/\-.]/g, '_')
      .replace(/\.html$/, '')

    barrel.push(`import ${exportName} from '${importPath}.js'`)
    exports.push(exportName)

    count++
  }

  barrel.push('')
  barrel.push(`export default { count: ${count} }`)

  if (exports.length > 0) {
    barrel.push(`export { ${exports.join(', ')} }`)
  }

  barrel.push('')

  const barrelDir = outputDir
  mkdirSync(barrelDir, { recursive: true })
  writeFileSync(join(barrelDir, 'index.js'), barrel.join('\n'))

  return { files: count, output: outputDir }
}
